apiVersion: v1
kind: ConfigMap
metadata:
  name: synchronizer-job-config
data:
  {{- if eq .Values.env "production" }}
  SYNCHRONIZER_URL: https://murmurations-synchronizer.vercel.app/api
  {{- else if eq .Values.env "staging" }}
  SYNCHRONIZER_URL: https://murmurations-synchronizer.vercel.app/api
  {{- else }}
  SYNCHRONIZER_URL: https://murmurations-synchronizer.vercel.app/api
  {{- end }}
