apiVersion: batch/v1
kind: CronJob
metadata:
  name: synchronizer-job
spec:
  schedule: "* * * * *"  # every minute
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: synchronizer-job
              image: {{ .Values.image }}
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: synchronizer-job-config
                - secretRef:
                    name: synchronizer-job-secret
              args: ["sh", "-c", "curl --request GET \ --url $(SYNCHRONIZER_URL) \ --header 'Authorization: Bearer $(API_SECRET_KEY)'"]
          restartPolicy: Never
