name: main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ secrets.PRODUCTION_SERVER_IP }}
      KUBECONFIG_PATH: ${{ secrets.KUBECONFIG_PATH }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DEPLOY_ENV: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH and Deploy Services
        run: ./scripts/deploy-services.sh
