name: main
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://murmurations-synchronizer.vercel.app/api' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'